# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "je-sbom-cve"
BBFILE_PATTERN_je-sbom-cve = "^${LAYERDIR}/"
BBFILE_PRIORITY_je-sbom-cve = "8"

LAYERDEPENDS_je-sbom-cve = "core"
LAYERSERIES_COMPAT_je-sbom-cve = "scarthgap"

LAYERDIR_JE_SBOM_CVE = "${LAYERDIR}"
