# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "je-detection"
BBFILE_PATTERN_je-detection = "^${LAYERDIR}/"
BBFILE_PRIORITY_je-detection = "8"

LAYERDEPENDS_je-detection = "core"
LAYERSERIES_COMPAT_je-detection = "scarthgap"

LAYERDIR_JE_DETECTION = "${LAYERDIR}"
