# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "je-hygiene"
BBFILE_PATTERN_je-hygiene = "^${LAYERDIR}/"
BBFILE_PRIORITY_je-hygiene = "8"

LAYERDEPENDS_je-hygiene = "core"
LAYERSERIES_COMPAT_je-hygiene = "scarthgap"

LAYERDIR_JE_HYGIENE = "${LAYERDIR}"
