# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "je-boot-update"
BBFILE_PATTERN_je-boot-update = "^${LAYERDIR}/"
BBFILE_PRIORITY_je-boot-update = "8"

LAYERDEPENDS_je-boot-update = "core"
LAYERSERIES_COMPAT_je-boot-update = "scarthgap"

LAYERDIR_JE_BOOT_UPDATE = "${LAYERDIR}"
